baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SMC'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[[params.socialIcons]]
name = "github"
url = "https://github.com/AbesM"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/SebastianMatiaC"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"





[params]
  goToTop = true
  math = true

 [params.author]
 avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "SMC Blog "
  name = "Seba"
  description = "A blog where I just collect some random math toughts."

  [menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = 'https://abesm.github.io/Hugo_Site/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
    [[menu.main]]
    pageRef="books"
    name = 'Books'
    url = '/posts/LibriDaleggere/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/pages/about/'
    weight = 30